# Generated by Django 2.2 on 2019-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190417_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje', models.CharField(max_length=200)),
                ('corriente', models.CharField(max_length=200)),
                ('potencia', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=20),
        ),
    ]
